### ISSUE TITLE
Can't connect via LAN with mod installed

### ISSUE THREAD

**Issue by ghost** [Belgabor/ExtraTweaker#1]
using latest version, 1.10.2 with craft tweaker 1.10.2 version. Says: Fatal Error when some tries to load into the game. Works fine singleplayer. Not tested on server. Scripts contain change to vanilla and modded block harvest levels

**Comment by Belgabor** [comment]
Very odd.
Do all clients have the script(s) installed?
Does it work without the scripts and/or ExtraTweaker?

In any case, could you attach your script(s) so I can have a look?

**Comment by skruis** [comment]
Running into the same issue here but only in MP. SP is working perfectly. I've attached my log. You'll find the error at line 27991.

[fml-client-3.zip](https://github.com/Belgabor/ExtraTweaker/files/593221/fml-client-3.zip)

**Comment by Belgabor** [comment]
Could you guys please test https://github.com/Belgabor/ExtraTweaker/releases/tag/v0.31pre and see if that fixes the issue?

**Comment by skruis** [comment]
That seems to have done it. Any idea of a timeline for release?
