### ISSUE TITLE
Wheres config file?

### ISSUE THREAD

**Issue by deividaslord** [Belgabor/ExtraTweaker#2]
Hello i want to change durability on some tools, but cant seem to find your config file. Is it in the same MineTweakerRecipeMaker.zs file? Where should i write in then?

**Comment by Belgabor** [comment]
Yes, it extends the syntax of Mine-/Crafttweaker, so it goes into a .zs file in the scripts folder.

**Comment by deividaslord** [comment]
But it dindt create a new line? I do still only have marker remove shapeless/shaped, add shapeless/shaped.
So where should i add for ex. mods.vanilla.Durability.set(<minecraft:wooden_pickaxe>, 2); ? In the recipe?
And how about the picture you display as mod logo, where can i find that? Because that seems as a easier way to edit item data.

![image](https://cloud.githubusercontent.com/assets/24681210/21468804/4d5481fc-ca28-11e6-9298-0953b89cec53.png)
